name: 'Run Test Kitchen'
description: 'Runs Test Kitchen tests with configurable options'

inputs:
  suite:
    description: 'Test Kitchen suite to run'
    required: true
  os:
    description: 'Operating system to test'
    required: true
  kitchen-yaml:
    description: 'Kitchen YAML file to use'
    required: false
    default: 'kitchen.dokken.yml'
  chef-version:
    description: 'Chef version to use'
    required: false
    default: 'current'
  chef-license:
    description: 'Chef license acceptance'
    required: false
    default: 'accept-no-persist'
  kitchen-command:
    description: 'Kitchen command to run (test, verify, etc)'
    required: false
    default: 'test'
  channel:
    description: 'Chef download channel'
    required: false
    default: 'stable'
  project:
    description: 'Chef project to download'
    required: false
    default: 'chef-workstation'
  version:
    description: 'Version of Chef product'
    required: false
  windowsPath:
    description: 'Windows installation path'
    required: false
    default: 'C:\opscode'

runs:
  using: "composite"
  steps:
    - name: Install Chef
      uses: ./.github/actions/chef-install
      with:
        version: ${{ inputs.chef-version }}
        chef-license: ${{ inputs.chef-license }}

    - name: Run Test Kitchen
      shell: bash
      run: kitchen ${{ inputs.kitchen-command }} ${{ inputs.suite }}-${{ inputs.os }}
      env:
        CHEF_LICENSE: ${{ inputs.chef-license }}
        KITCHEN_LOCAL_YAML: ${{ inputs.kitchen-yaml }}
        KITCHEN_YAML: ${{ inputs.kitchen-yaml }}
