---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@main
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os:
          - almalinux-9
          - almalinux-10
          - amazonlinux-2023
          - centos-stream-9
          - centos-stream-10
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - oraclelinux-8
          - oraclelinux-9
          - ubuntu-2204
          - ubuntu-2404
        suite:
          - "installation-script-main"
          - "installation-script-test"
          - "installation-package"
          - "installation-tarball"
          - "install-and-stop"
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test Kitchen
        uses: ./.github/actions/test-kitchen
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          kitchen-yaml: kitchen.dokken.yml
          chef-version: latest
          chef-license: accept-no-persist

  integration-swarm:
    needs: lint-unit
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: ["ubuntu-2204"]
        suite: ["swarm"]
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup VirtualBox & Vagrant
        uses: ./.github/actions/virtualbox-setup
      - name: Run Kitchen Tests
        uses: ./.github/actions/test-kitchen
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          kitchen-yaml: kitchen.yml
          chef-version: latest
          chef-license: accept-no-persist

  integration-smoke:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "debian-11"
          - "debian-12"
          - "rockylinux-8"
          - "rockylinux-9"
          - "ubuntu-2004"
          - "ubuntu-2204"
          - "ubuntu-2404"
        suite:
          - "smoke"
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup VirtualBox & Vagrant
        uses: ./.github/workflows/virtualbox-setup.yml
      - name: Install Chef
        uses: actionshub/chef-install@3.0.1
      - name: Test Kitchen
        uses: ./.github/actions/test-kitchen
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          kitchen-yaml: kitchen.yml
          chef-version: latest
          chef-license: accept-no-persist
